### ISSUE TITLE
Bugged conversion

### ISSUE THREAD

**Issue by leonardofmed** [jdesboeufs/geojson2shp#2]
Using this library generate a shp file, but don't represent the original file.

What I'm doing:
```
const {convert} = require('geojson2shp')

const options = {
  layer: 'my-layer',
  targetCrs: 31982
}

async function converter() {
	await convert('./agricultura.geojson', './dest-shp.zip', options)
}
converter();
```
The original file:
![originalGeoJSON](https://user-images.githubusercontent.com/33374703/61819855-3acec680-ae2a-11e9-8d0e-bef46e5c2c82.jpg)

The generated one:
![createdSHP](https://user-images.githubusercontent.com/33374703/61819882-46ba8880-ae2a-11e9-98f3-0c8a9d0c7223.jpg)

If I'm missing something, please let me know.

**Comment by jdesboeufs** [comment]
Woow very artistic! :D

**Comment by jdesboeufs** [comment]
Can you attach an example file?

**Comment by leonardofmed** [comment]
Hi, I managed to convert the file using gdal's [`ogr2ogr`](https://gdal.org/programs/ogr2ogr.html) this way:
```
args = ["ogr2ogr", "-f", "ESRI Shapefile", "-a_srs", "EPSG:31982", "/processed_files/filename.shp", "/geojson_files/mygeojson.geojson"]
subprocess.Popen(args).wait()
```

**Comment by jdesboeufs** [comment]
I don't understand. Is it finally working?

**Comment by leonardofmed** [comment]
Sorry, I didn't explained very well. I ended giving up of this library and used the python's GDAL library directly, as show in my previous comment. Thank you anyway.
